# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#

inherit_from:
  - '.rubocop_todo.yml'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - 'db/schema.rb'
    - '**/config.ru'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/spec_helper.rb'
    - '**/rails_helper.rb'
    - 'bin/*'
    - '**/config/**/*'

###########################################################
###################### RuboCop ############################
###########################################################

# You can find all configuration options for rubocop here: https://docs.rubocop.org/rubocop/cops_bundler.html

###########################################################
######################## Layout ###########################
###########################################################

Layout/ClassStructure:
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - initializer
    - public_class_methods
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

###########################################################
######################## Metric ###########################
###########################################################

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'
    - '**/factories/**/*'

###########################################################
######################## Rspec ###########################
###########################################################

RSpec/ExampleLength:
  Exclude:
    - '**/spec/**/*'

###########################################################
######################## Style ############################
###########################################################

Style/Documentation:
  Enabled: false
